export const CREATE_EVENT_ITEM = "CREATE_EVENT_ITEM";
export const COMPLETE_EVENT_ITEM = "COMPLETE_EVENT_ITEM";
export const REMOVE_EVENT_ITEM = "REMOVE_EVENT_ITEM";
export const SEARCH_EVENT_ITEM = "SEARCH_EVENT_ITEM";
export const FILTER_EVENT_ITEM = "FILTER_EVENT_ITEM";
export const EDIT_EVENT_ITEM = "EDIT_EVENT_ITEM";
